export const TREATMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
};

export const TREATMENT_STATUS_LABELS = {
  [TREATMENT_STATUS.ACTIVE]: 'Active',
  [TREATMENT_STATUS.COMPLETED]: 'Completed',
  [TREATMENT_STATUS.PENDING]: 'Pending',
  [TREATMENT_STATUS.CANCELLED]: 'Cancelled',
};

export const TREATMENT_STATUS_COLORS = {
  [TREATMENT_STATUS.ACTIVE]: 'success',
  [TREATMENT_STATUS.COMPLETED]: 'default',
  [TREATMENT_STATUS.PENDING]: 'warning',
  [TREATMENT_STATUS.CANCELLED]: 'error',
};
